### ISSUE TITLE
phpunit integration

### ISSUE THREAD

**Issue by spdionis** [padraic/mockery#376]
If a test function does not make any assert then phpunit complains about "risky test" and Phpstorm says "This test did not perform any assertions".

I have added Mockery's listener to phpunit.xml. I've also tried to do \Mockery::close() in the tearDown() method.

Mockery's expectations still work as intended. They break when they should. Currently i fix the issue adding $this->assertTrue(true); in every test.

Phpunit version is 4.2.6 and Mockery version is 0.9.2

**Comment by gknapp** [comment]
I'm seeing this issue in PHPUnit 4.6.0 with Mockery 0.9.4 - if I just use a mock Doctrine DBAL connection and have no assertions in the test, it's marked as risky with `beStrictAboutTestsThatDoNotTestAnything="true"` in my phpunit.xml

**Comment by aik099** [comment]
Yes, mockery's mock expectation don't add-up to assertion count made in the test. That's why test is marked as risky. It's impossible to do this via PHPUnit hook. What you want is to call `\Mockery::close();` in your `tearDown` method or just use the proposed trait in your unit test.

**Comment by halaei** [comment]
Using the proposed trait, this test is not marked as risky, although it really tests nothing:
```php
function test_nothing()
{
    $c = Mockery::mock(C::class);
    $c->shouldReceive('f');
}
```
Is there a fix for it as well?

**Comment by XedinUnknown** [comment]
Still experiencing this with PHPUnit 6, and Mockery 1.2. Adding `Mockery::close()` or the `addToAssertionCount()` thing didn't work: still marks tests as risky.

**Comment by XedinUnknown** [comment]
Fixed. Apparently, gotta just use the `Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration` trait in the test case.

**Comment by reza305z** [comment]
experiencing it too with shouldReceive() method, but not with shouldNotReceive(). Using PHPUnit 9, and Mockery 1.4. Adding Mockery\Adapter\Phpunit\MockeryPHPUnitIntegration trait in test case didn't work. I'm using Pest 1.16 by the way.
Only thing that can help is adding this method:

``
test('some_test', function() {

    $this->expectNotToPerformAssertions();
    $this->someMockedInterface->shouldReceive('someMethod');
    // ...

});
``

**Comment by mfn** [comment]
This is because of the latest version: your `shouldReceive` has no _actual_ expectation set yet. It needs `->once()` or `->times()`. Or, instead of `shouldReceive`, you can use `expects`.

**Comment by smitit1999** [comment]
@mfn thank you so much. I tried implementing the `tearDown` method but the test was still failing. Added the `times` check and it passed like a charm
